// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int readme_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int readme = 9;
	/// <summary>PID: 101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int fakesctehexvalue_101 = 101;
	/// <summary>PID: 101 | Type: read</summary>
	public const int fakesctehexvalue = 101;
	/// <summary>PID: 102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int fakesctestream_102 = 102;
	/// <summary>PID: 102 | Type: read</summary>
	public const int fakesctestream = 102;
	/// <summary>PID: 103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int fakescteprogram_103 = 103;
	/// <summary>PID: 103 | Type: read</summary>
	public const int fakescteprogram = 103;
	/// <summary>PID: 104 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int fakescteoperationname_104 = 104;
	/// <summary>PID: 104 | Type: read</summary>
	public const int fakescteoperationname = 104;
	/// <summary>PID: 105 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int fakescteipaddress_105 = 105;
	/// <summary>PID: 105 | Type: read</summary>
	public const int fakescteipaddress = 105;
	/// <summary>PID: 7999999 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int lastprimarykey_7999999 = 7999999;
	/// <summary>PID: 7999999 | Type: read</summary>
	public const int lastprimarykey = 7999999;
	public class Write
	{
		/// <summary>PID: 100 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fakesctepagebutton_100 = 100;
		/// <summary>PID: 100 | Type: write</summary>
		public const int fakesctepagebutton = 100;
		/// <summary>PID: 151 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fakesctehexvalue_151 = 151;
		/// <summary>PID: 151 | Type: write</summary>
		public const int fakesctehexvalue = 151;
		/// <summary>PID: 152 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fakesctestream_152 = 152;
		/// <summary>PID: 152 | Type: write</summary>
		public const int fakesctestream = 152;
		/// <summary>PID: 153 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fakescteprogram_153 = 153;
		/// <summary>PID: 153 | Type: write</summary>
		public const int fakescteprogram = 153;
		/// <summary>PID: 154 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fakescteoperationname_154 = 154;
		/// <summary>PID: 154 | Type: write</summary>
		public const int fakescteoperationname = 154;
		/// <summary>PID: 155 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fakescteipaddress_155 = 155;
		/// <summary>PID: 155 | Type: write</summary>
		public const int fakescteipaddress = 155;
		/// <summary>PID: 199 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fakesctebutton_199 = 199;
		/// <summary>PID: 199 | Type: write</summary>
		public const int fakesctebutton = 199;
	}
	public class Scte
	{
		/// <summary>PID: 8000000</summary>
		public const int tablePid = 8000000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 8000001</summary>
		public const int indexColumnPid = 8000001;
		public class Pid
		{
			/// <summary>PID: 8000001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_key_8000001 = 8000001;
			/// <summary>PID: 8000001 | Type: read</summary>
			public const int scte_key = 8000001;
			/// <summary>PID: 8000002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_ts_8000002 = 8000002;
			/// <summary>PID: 8000002 | Type: read</summary>
			public const int scte_ts = 8000002;
			/// <summary>PID: 8000003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_opid_8000003 = 8000003;
			/// <summary>PID: 8000003 | Type: read</summary>
			public const int scte_opid = 8000003;
			/// <summary>PID: 8000004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_opname_8000004 = 8000004;
			/// <summary>PID: 8000004 | Type: read</summary>
			public const int scte_opname = 8000004;
			/// <summary>PID: 8000005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_src_8000005 = 8000005;
			/// <summary>PID: 8000005 | Type: read</summary>
			public const int scte_src = 8000005;
			/// <summary>PID: 8000006 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_str_8000006 = 8000006;
			/// <summary>PID: 8000006 | Type: read</summary>
			public const int scte_str = 8000006;
			/// <summary>PID: 8000007 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_pgm_8000007 = 8000007;
			/// <summary>PID: 8000007 | Type: read</summary>
			public const int scte_pgm = 8000007;
			/// <summary>PID: 8000008 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_obj_8000008 = 8000008;
			/// <summary>PID: 8000008 | Type: read</summary>
			public const int scte_obj = 8000008;
			/// <summary>PID: 8000009 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_segevntid_8000009 = 8000009;
			/// <summary>PID: 8000009 | Type: read</summary>
			public const int scte_segevntid = 8000009;
			/// <summary>PID: 8000010 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_segupid_8000010 = 8000010;
			/// <summary>PID: 8000010 | Type: read</summary>
			public const int scte_segupid = 8000010;
			/// <summary>PID: 8000011 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_segtypeid_8000011 = 8000011;
			/// <summary>PID: 8000011 | Type: read</summary>
			public const int scte_segtypeid = 8000011;
			/// <summary>PID: 8000012 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_segtypename_8000012 = 8000012;
			/// <summary>PID: 8000012 | Type: read</summary>
			public const int scte_segtypename = 8000012;
			/// <summary>PID: 8000013 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_fld1_8000013 = 8000013;
			/// <summary>PID: 8000013 | Type: read</summary>
			public const int scte_fld1 = 8000013;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_key_8000001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int scte_key = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_ts_8000002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int scte_ts = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_opid_8000003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int scte_opid = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_opname_8000004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int scte_opname = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_src_8000005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int scte_src = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_str_8000006 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int scte_str = 5;
			/// <summary>IDX: 6 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_pgm_8000007 = 6;
			/// <summary>IDX: 6 | Type: read</summary>
			public const int scte_pgm = 6;
			/// <summary>IDX: 7 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_obj_8000008 = 7;
			/// <summary>IDX: 7 | Type: read</summary>
			public const int scte_obj = 7;
			/// <summary>IDX: 8 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_segevntid_8000009 = 8;
			/// <summary>IDX: 8 | Type: read</summary>
			public const int scte_segevntid = 8;
			/// <summary>IDX: 9 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_segupid_8000010 = 9;
			/// <summary>IDX: 9 | Type: read</summary>
			public const int scte_segupid = 9;
			/// <summary>IDX: 10 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_segtypeid_8000011 = 10;
			/// <summary>IDX: 10 | Type: read</summary>
			public const int scte_segtypeid = 10;
			/// <summary>IDX: 11 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_segtypename_8000012 = 11;
			/// <summary>IDX: 11 | Type: read</summary>
			public const int scte_segtypename = 11;
			/// <summary>IDX: 12 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int scte_fld1_8000013 = 12;
			/// <summary>IDX: 12 | Type: read</summary>
			public const int scte_fld1 = 12;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 100  | Type: write | DISCREETS: Fake SCTE Event... = Fake SCTE Event</summary>
	public System.Object Fakesctepagebutton {get { return Protocol.GetParameter(100); }set { Protocol.SetParameter(100, value); }}
	/// <summary>PID: 151  | Type: write</summary>
	public System.Object Fakesctehexvalue {get { return Protocol.GetParameter(151); }set { Protocol.SetParameter(151, value); }}
	/// <summary>PID: 152  | Type: write</summary>
	public System.Object Fakesctestream {get { return Protocol.GetParameter(152); }set { Protocol.SetParameter(152, value); }}
	/// <summary>PID: 153  | Type: write</summary>
	public System.Object Fakescteprogram {get { return Protocol.GetParameter(153); }set { Protocol.SetParameter(153, value); }}
	/// <summary>PID: 154  | Type: write</summary>
	public System.Object Fakescteoperationname {get { return Protocol.GetParameter(154); }set { Protocol.SetParameter(154, value); }}
	/// <summary>PID: 155  | Type: write</summary>
	public System.Object Fakescteipaddress {get { return Protocol.GetParameter(155); }set { Protocol.SetParameter(155, value); }}
	/// <summary>PID: 199  | Type: write | DISCREETS: Fake Event = 1</summary>
	public System.Object Fakesctebutton {get { return Protocol.GetParameter(199); }set { Protocol.SetParameter(199, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 8000000</summary>
	ScteQActionTable scte { get; set; }
	object Readme_9 { get; set; }
	object Readme { get; set; }
	object Fakesctepagebutton_100 { get; set; }
	object Fakesctepagebutton { get; set; }
	object Fakesctehexvalue_101 { get; set; }
	object Fakesctehexvalue { get; set; }
	object Fakesctestream_102 { get; set; }
	object Fakesctestream { get; set; }
	object Fakescteprogram_103 { get; set; }
	object Fakescteprogram { get; set; }
	object Fakescteoperationname_104 { get; set; }
	object Fakescteoperationname { get; set; }
	object Fakescteipaddress_105 { get; set; }
	object Fakescteipaddress { get; set; }
	object Fakesctehexvalue_151 { get; set; }
	object Fakesctestream_152 { get; set; }
	object Fakescteprogram_153 { get; set; }
	object Fakescteoperationname_154 { get; set; }
	object Fakescteipaddress_155 { get; set; }
	object Fakesctebutton_199 { get; set; }
	object Fakesctebutton { get; set; }
	object Lastprimarykey_7999999 { get; set; }
	object Lastprimarykey { get; set; }
	object Scte_key_8000001 { get; set; }
	object Scte_key { get; set; }
	object Scte_ts_8000002 { get; set; }
	object Scte_ts { get; set; }
	object Scte_opid_8000003 { get; set; }
	object Scte_opid { get; set; }
	object Scte_opname_8000004 { get; set; }
	object Scte_opname { get; set; }
	object Scte_src_8000005 { get; set; }
	object Scte_src { get; set; }
	object Scte_str_8000006 { get; set; }
	object Scte_str { get; set; }
	object Scte_pgm_8000007 { get; set; }
	object Scte_pgm { get; set; }
	object Scte_obj_8000008 { get; set; }
	object Scte_obj { get; set; }
	object Scte_segevntid_8000009 { get; set; }
	object Scte_segevntid { get; set; }
	object Scte_segupid_8000010 { get; set; }
	object Scte_segupid { get; set; }
	object Scte_segtypeid_8000011 { get; set; }
	object Scte_segtypeid { get; set; }
	object Scte_segtypename_8000012 { get; set; }
	object Scte_segtypename { get; set; }
	object Scte_fld1_8000013 { get; set; }
	object Scte_fld1 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 8000000</summary>
	public ScteQActionTable scte { get; set; }
	/// <summary>PID: 9  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Readme_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	public System.Object Readme {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 100  | Type: write | DISCREETS: Fake SCTE Event... = Fake SCTE Event</summary>
	public System.Object Fakesctepagebutton_100 {get { return GetParameter(100); }set { SetParameter(100, value); }}
	/// <summary>PID: 100  | Type: write | DISCREETS: Fake SCTE Event... = Fake SCTE Event</summary>
	public System.Object Fakesctepagebutton {get { return Write.Fakesctepagebutton; }set { Write.Fakesctepagebutton = value; }}
	/// <summary>PID: 101  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakesctehexvalue_101 {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 101  | Type: read</summary>
	public System.Object Fakesctehexvalue {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 102  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakesctestream_102 {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 102  | Type: read</summary>
	public System.Object Fakesctestream {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 103  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakescteprogram_103 {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 103  | Type: read</summary>
	public System.Object Fakescteprogram {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 104  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakescteoperationname_104 {get { return GetParameter(104); }set { SetParameter(104, value); }}
	/// <summary>PID: 104  | Type: read</summary>
	public System.Object Fakescteoperationname {get { return GetParameter(104); }set { SetParameter(104, value); }}
	/// <summary>PID: 105  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakescteipaddress_105 {get { return GetParameter(105); }set { SetParameter(105, value); }}
	/// <summary>PID: 105  | Type: read</summary>
	public System.Object Fakescteipaddress {get { return GetParameter(105); }set { SetParameter(105, value); }}
	/// <summary>PID: 151  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakesctehexvalue_151 {get { return GetParameter(151); }set { SetParameter(151, value); }}
	/// <summary>PID: 152  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakesctestream_152 {get { return GetParameter(152); }set { SetParameter(152, value); }}
	/// <summary>PID: 153  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakescteprogram_153 {get { return GetParameter(153); }set { SetParameter(153, value); }}
	/// <summary>PID: 154  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakescteoperationname_154 {get { return GetParameter(154); }set { SetParameter(154, value); }}
	/// <summary>PID: 155  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fakescteipaddress_155 {get { return GetParameter(155); }set { SetParameter(155, value); }}
	/// <summary>PID: 199  | Type: write | DISCREETS: Fake Event = 1</summary>
	public System.Object Fakesctebutton_199 {get { return GetParameter(199); }set { SetParameter(199, value); }}
	/// <summary>PID: 199  | Type: write | DISCREETS: Fake Event = 1</summary>
	public System.Object Fakesctebutton {get { return Write.Fakesctebutton; }set { Write.Fakesctebutton = value; }}
	/// <summary>PID: 7999999  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Lastprimarykey_7999999 {get { return GetParameter(7999999); }set { SetParameter(7999999, value); }}
	/// <summary>PID: 7999999  | Type: read</summary>
	public System.Object Lastprimarykey {get { return GetParameter(7999999); }set { SetParameter(7999999, value); }}
	/// <summary>PID: 8000001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_key_8000001 {get { return GetParameter(8000001); }set { SetParameter(8000001, value); }}
	/// <summary>PID: 8000001  | Type: read</summary>
	public System.Object Scte_key {get { return GetParameter(8000001); }set { SetParameter(8000001, value); }}
	/// <summary>PID: 8000002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_ts_8000002 {get { return GetParameter(8000002); }set { SetParameter(8000002, value); }}
	/// <summary>PID: 8000002  | Type: read</summary>
	public System.Object Scte_ts {get { return GetParameter(8000002); }set { SetParameter(8000002, value); }}
	/// <summary>PID: 8000003  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_opid_8000003 {get { return GetParameter(8000003); }set { SetParameter(8000003, value); }}
	/// <summary>PID: 8000003  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Scte_opid {get { return GetParameter(8000003); }set { SetParameter(8000003, value); }}
	/// <summary>PID: 8000004  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_opname_8000004 {get { return GetParameter(8000004); }set { SetParameter(8000004, value); }}
	/// <summary>PID: 8000004  | Type: read</summary>
	public System.Object Scte_opname {get { return GetParameter(8000004); }set { SetParameter(8000004, value); }}
	/// <summary>PID: 8000005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_src_8000005 {get { return GetParameter(8000005); }set { SetParameter(8000005, value); }}
	/// <summary>PID: 8000005  | Type: read</summary>
	public System.Object Scte_src {get { return GetParameter(8000005); }set { SetParameter(8000005, value); }}
	/// <summary>PID: 8000006  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_str_8000006 {get { return GetParameter(8000006); }set { SetParameter(8000006, value); }}
	/// <summary>PID: 8000006  | Type: read</summary>
	public System.Object Scte_str {get { return GetParameter(8000006); }set { SetParameter(8000006, value); }}
	/// <summary>PID: 8000007  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_pgm_8000007 {get { return GetParameter(8000007); }set { SetParameter(8000007, value); }}
	/// <summary>PID: 8000007  | Type: read</summary>
	public System.Object Scte_pgm {get { return GetParameter(8000007); }set { SetParameter(8000007, value); }}
	/// <summary>PID: 8000008  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_obj_8000008 {get { return GetParameter(8000008); }set { SetParameter(8000008, value); }}
	/// <summary>PID: 8000008  | Type: read</summary>
	public System.Object Scte_obj {get { return GetParameter(8000008); }set { SetParameter(8000008, value); }}
	/// <summary>PID: 8000009  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_segevntid_8000009 {get { return GetParameter(8000009); }set { SetParameter(8000009, value); }}
	/// <summary>PID: 8000009  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Scte_segevntid {get { return GetParameter(8000009); }set { SetParameter(8000009, value); }}
	/// <summary>PID: 8000010  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_segupid_8000010 {get { return GetParameter(8000010); }set { SetParameter(8000010, value); }}
	/// <summary>PID: 8000010  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Scte_segupid {get { return GetParameter(8000010); }set { SetParameter(8000010, value); }}
	/// <summary>PID: 8000011  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_segtypeid_8000011 {get { return GetParameter(8000011); }set { SetParameter(8000011, value); }}
	/// <summary>PID: 8000011  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Scte_segtypeid {get { return GetParameter(8000011); }set { SetParameter(8000011, value); }}
	/// <summary>PID: 8000012  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_segtypename_8000012 {get { return GetParameter(8000012); }set { SetParameter(8000012, value); }}
	/// <summary>PID: 8000012  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Scte_segtypename {get { return GetParameter(8000012); }set { SetParameter(8000012, value); }}
	/// <summary>PID: 8000013  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_fld1_8000013 {get { return GetParameter(8000013); }set { SetParameter(8000013, value); }}
	/// <summary>PID: 8000013  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Scte_fld1 {get { return GetParameter(8000013); }set { SetParameter(8000013, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		scte = new ScteQActionTable(this, 8000000, "scte");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class ScteQActionTable : QActionTable, IEnumerable<ScteQActionRow>
{
	public ScteQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<ScteQActionRow> GetEnumerator() { return new QActionTableEnumerator<ScteQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class ScteQActionRow : QActionTableRow
{
	/// <summary>PID: 8000001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_key_8000001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 8000001 | Type: read</summary>
	public System.Object Scte_key { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 8000002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_ts_8000002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 8000002 | Type: read</summary>
	public System.Object Scte_ts { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 8000003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_opid_8000003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 8000003 | Type: read</summary>
	public System.Object Scte_opid { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 8000004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_opname_8000004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 8000004 | Type: read</summary>
	public System.Object Scte_opname { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 8000005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_src_8000005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 8000005 | Type: read</summary>
	public System.Object Scte_src { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 8000006 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_str_8000006 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 8000006 | Type: read</summary>
	public System.Object Scte_str { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 8000007 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_pgm_8000007 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 8000007 | Type: read</summary>
	public System.Object Scte_pgm { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 8000008 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_obj_8000008 { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
	/// <summary>PID: 8000008 | Type: read</summary>
	public System.Object Scte_obj { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
	/// <summary>PID: 8000009 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_segevntid_8000009 { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
	/// <summary>PID: 8000009 | Type: read</summary>
	public System.Object Scte_segevntid { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
	/// <summary>PID: 8000010 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_segupid_8000010 { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
	/// <summary>PID: 8000010 | Type: read</summary>
	public System.Object Scte_segupid { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
	/// <summary>PID: 8000011 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_segtypeid_8000011 { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
	/// <summary>PID: 8000011 | Type: read</summary>
	public System.Object Scte_segtypeid { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
	/// <summary>PID: 8000012 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_segtypename_8000012 { get { if (base.Columns.ContainsKey(11)) { return base.Columns[11]; } else { return null; } } set { if (base.Columns.ContainsKey(11)) { base.Columns[11] = value; } else { base.Columns.Add(11, value); } } }
	/// <summary>PID: 8000012 | Type: read</summary>
	public System.Object Scte_segtypename { get { if (base.Columns.ContainsKey(11)) { return base.Columns[11]; } else { return null; } } set { if (base.Columns.ContainsKey(11)) { base.Columns[11] = value; } else { base.Columns.Add(11, value); } } }
	/// <summary>PID: 8000013 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Scte_fld1_8000013 { get { if (base.Columns.ContainsKey(12)) { return base.Columns[12]; } else { return null; } } set { if (base.Columns.ContainsKey(12)) { base.Columns[12] = value; } else { base.Columns.Add(12, value); } } }
	/// <summary>PID: 8000013 | Type: read</summary>
	public System.Object Scte_fld1 { get { if (base.Columns.ContainsKey(12)) { return base.Columns[12]; } else { return null; } } set { if (base.Columns.ContainsKey(12)) { base.Columns[12] = value; } else { base.Columns.Add(12, value); } } }
	public ScteQActionRow() : base(0, 13) { }
	public ScteQActionRow(System.Object[] oRow) : base(0, 13, oRow) { }
	public static implicit operator ScteQActionRow(System.Object[] source) { return new ScteQActionRow(source); }
	public static implicit operator System.Object[](ScteQActionRow source) { return source.ToObjectArray(); }
}
}
